### ISSUE TITLE
Tidy, BBedit, Firefox

### ISSUE THREAD

**Issue by ferrenm** [htacg/htacg.github.io#3]
Running Macos Sierra, I installed Tidy yesterday. Looking at it briefly, it I get the impression that both BBEdit and Firefox call it to do their  HTML checking. If this is true, it seems that there is no incentive for me to learn to use Tidy directly, and that these applications will automatically use the new version. It might save newbies a lot of thrashing if the ReadMe mentioned this fact. 
Is it indeed a fact?

**Comment by balthisar** [comment]
@ferrenm, versions of BBEdit prior to version 11 included Tidy, but it was _not_ an up to date version of Tidy. FireFox does not include HTML Tidy in any form.

macOS Sierra includes HTML Tidy as a Terminal program and system library, but it's horribly, horribly outdated.

Tidy's not really all that hard to learn, but if you prefer something easy to use, consider using [Balthisar Tidy](http://www.balthisar.com/software/tidy/). It gives you a really nice interface for playing with all of Tidy's configuration options, and you can see the results instantly. It also works with BBEdit via System Services, and standard Cocoa apps as an action extension, if you like.
